import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/custom/header";
import { Jura } from 'next/font/google'

const jura = Jura({
    weight: ['300', '700'],
    style: ['normal'],
    subsets: ['latin'], 
  })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jura.className}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
